name: Windows release build

on:
  workflow_dispatch:

jobs:
  build-win64:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Configure git
        shell: pwsh
        run: |
          git config --global core.longpaths true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Prepare dependencies
        shell: cmd
        env:
          TDESKTOP_SKIP_DUMP_SYMS: "1"
        run: |
          Telegram\build\prepare\win.bat

      - name: Configure
        shell: cmd
        run: |
          cd Telegram
          configure.bat x64 -D TDESKTOP_API_ID=2040 -D TDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627

      - name: Expand pagefile
        shell: pwsh
        run: |
          $computer = Get-CimInstance Win32_ComputerSystem
          $computer.AutomaticManagedPagefile = $false
          Set-CimInstance -InputObject $computer
          $pagefile = Get-CimInstance Win32_PageFileSetting | Where-Object { $_.Name -eq "D:\pagefile.sys" }
          if (-not $pagefile) {
            New-CimInstance -ClassName Win32_PageFileSetting -Property @{ Name = "D:\pagefile.sys"; InitialSize = [uint32]16384; MaximumSize = [uint32]32768 }
          } else {
            $pagefile.InitialSize = [uint32]16384
            $pagefile.MaximumSize = [uint32]32768
            Set-CimInstance -InputObject $pagefile
          }

      - name: Build Release
        shell: cmd
        run: |
          cmake --build out --config Release --target Telegram --parallel 1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-7.0.5-windows-x64-portable
          path: |
            out/Release/**
            !out/Release/**/*.pdb
            !out/Release/**/*.ilk
            !out/Release/**/*.exp
            !out/Release/**/*.lib
          if-no-files-found: error
          compression-level: 9
